[versions]
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
compile-sdk = "35"
min-sdk = "24"
version-code = "1"
java-version = "17"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
